### ISSUE TITLE
Changed repository location

### ISSUE THREAD

**Issue by Gaya** [ThymeApp/thyme#181]
This is just an update for people looking into helping out with this repository.

I move the repositories connected to Thyme from my personal account to an organisation account. This will help in keeping a clear overview of running projects connected to Thyme.

Please update your remotes to `git@github.com:ThymeApp/thyme.git`

**Comment by Gaya** [comment]
cc: @Scoombe

**Comment by Scoombe** [comment]
@Gaya Cheers, it's all looking good!
