### ISSUE TITLE
Add front-end option to set the sync service location

### ISSUE THREAD

**Issue by rosswintle** [ThymeApp/thyme#186]
First of all - great work! And thanks for chatting on Twitter this morning.

Love the concept of this.

It seems unnecessary to clone the whole repo and host it yourself just to change the sync service location.

Could you add some settings to the app to enable this to be configured from inside the app? The everyone can just use a single, up-to-date usethyme.com instance for the app, but run their own back-end if they want to.

Just an idea. Hope you can make it happen.

Thanks

**Comment by Gaya** [comment]
Great idea, Ross.

Will add this as a new setting on the settings page.

**Comment by Gaya** [comment]
When PR is merged the API root can be entered manually in the settings page.

Implementation details for a backend will follow. More information available in #189
