### ISSUE TITLE
Automatically select last picked project for new items

### ISSUE THREAD

**Issue by Gaya** [ThymeApp/thyme#229]
Leaving the last project selected can improve fasting logging of items.

**Comment by Scoombe** [comment]
@Gaya I can look at this if you like? Anything I should know before starting? Just use the component state to keep the project selected?

**Comment by Gaya** [comment]
@Scoombe I changed the Entry component to be fully controlled. You can find the `New` component now controls the temporary Entry until it gets added to the store for good.

https://github.com/ThymeApp/thyme/blob/master/src/sections/TimeSheet/components/Entry/New.js#L127

This is a good place to start looking. Before the component "resets" we could get the current project and provide it when resetting instead of clearing it, which is what happens at the moment.

**Comment by Gaya** [comment]
Thanks @Scoombe , closing this one
