### ISSUE TITLE
Using duration not start&end time

### ISSUE THREAD

**Issue by vanntile** [ThymeApp/thyme#304]
Is there any thought of using duration for a task instead of start & end time?

**Comment by Gaya** [comment]
This was an idea I had before. At first I didn't want to add it, but later it seemed like a good idea to be able to just enter time by duration.

It's already opened an issue: #303

**Comment by vanntile** [comment]
Oh, sorry, I didn't get it was the same issue. You can close this.

**Comment by Gaya** [comment]
I'll add this issue for clarification. Thanks for contributing.
